name: onelamarket_app
description: "Onela Market Mobile App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onela_box.png
    - assets/images/logo.png
    - assets/icons/ic_line.png
    - assets/icons/ic_google.png
    - assets/icons/ic_facebook.png
    - assets/icons/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-VariableFont_wdth,wght.ttf
